spring:
  redis:
    port: 6379
    host: localhost
  profiles:
    include: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:mariadb://rainbow-server-db.cgchmvhetcl5.ap-northeast-2.rds.amazonaws.com:3306/rainbow_db
      username: rainbow
      password: gwon188!!
      driver-class-name: org.mariadb.jdbc.Driver

oauth:
  kakao:
    client-id: b3ee341ecd11261443a552fa9fbe2d58
    client-secret: yZVqfZOgfiSuiVYH57BSDEXvpYQrs3eN
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

cloud:
  aws:
    credentials:
      access_key: {IAM access key}
      secret_key: {IAM secret key}
    s3:
      bucket: rainbow-image-upload-s3-bucket
      dir: image

    stack:
      auto: false

    region:
      static: ap-northeast-2
