spring:
  profiles:
    include: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://rainbow-server-db.cgchmvhetcl5.ap-northeast-2.rds.amazonaws.com:3306/rainbow_db
      username: rainbow
      password: gwon188!!
      driver-class-name: org.mariadb.jdbc.Driver

