spring:
  redis:
    port: 6379
    host: localhost
  profiles:
    include: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:mariadb://rainbow-server-db.cgchmvhetcl5.ap-northeast-2.rds.amazonaws.com:3306/rainbow_db
      username: rainbow
      password: gwon188!!
      driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 5MB

oauth:
  kakao:
    client-id: b3ee341ecd11261443a552fa9fbe2d58
    client-secret: yZVqfZOgfiSuiVYH57BSDEXvpYQrs3eN
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

cloud:
  aws:
    s3:
      bucket: rainbow-github-actions-s3-bucket
      dir: image/
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

